# other params to potentially include:
# HTTP headers/auth tokens
# query params
# retry settings
# target opensearch index (or opensearch connection info)
project: ICDC
sources:
  - name: IDC
    type: rest
    api_base_url: https://api.imaging.datacommons.cancer.gov/v1
    dataset_base_url: https://portal.imaging.datacommons.cancer.gov/explore/filters/?collection_id=
    endpoint: /collections
    response_data_key: collections  # optional key
    match_key: collection_id
    filter_prefix: icdc_
    post_processor: clean_idc_descriptions
  - name: TCIA
    type: rest
    api_base_url: https://services.cancerimagingarchive.net/services/v4
    dataset_base_url: https://nbia.cancerimagingarchive.net/nbia-search/?MinNumberOfStudiesCriteria=1&CollectionCriteria=
    discovery:
      endpoint: /TCIA/query/getCollectionValues
      match_key: Collection
      filter_prefix: ICDC-
    fetch:
      endpoint_template: /TCIA/query/getSeries?Collection={collection_id}
      key_param: collection_id
    post_processor: aggregate_tcia_series
  - name: ICDC
    type: graphql
    api_base_url: https://caninecommons-dev.cancer.gov
    endpoint: /graphql/
    query: |
      {
        studiesByProgram {
            clinical_study_designation
            numberOfImageCollections
            numberOfCRDCNodes
        }
      }
    method: POST # should probably be default for graphql types
